### ISSUE TITLE
aci_epg_to_static_path referencing interface policy group

### ISSUE THREAD

**Issue by MyUsernameIsTakenAgain** [CiscoDevNet/terraform-provider-aci#1052]
I could use the resource "aci_epg_to_static_path" to reference a port in a leaf such as
tdn  = "topology/pod-1/paths-101/pathep-[eth1/3]"

But I couldn't reference an interface policy group that is linked to a port-channel on a vPC of 2 leaves example
tdn  = aci_leaf_access_bundle_policy_group.PG-vPC-1

Is there any way to do that ?

Regards
Ali

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) + ACI Class(es):

* aci_XXXXX + fv:XXXX

### APIC version and APIC Platform

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by akinross** [comment]
Hi Ali,

I am not sure I am understanding what it is that you are trying to do exactly. I assume you are trying to provide the tDn of a vpc interface. This would be a dn of fabricPathEp and should have a format like the following: topology/pod-{pod-id}/protpaths-{node-ids}/pathep-[{pol-grp-name}]). 

I am not sure what you are passing into the tDn value with aci_leaf_access_bundle_policy_group.PG-vPC-1, but the id of this resource would be set to "uni/infra/funcprof/accbundle-{pol-grp-name}". Based on assumptions due to limited amount of information shared I think you would need to construct you tDn differently. See below example ( be aware of the static pod and node ids in the tdn string.

```
resource "aci_leaf_access_bundle_policy_group" "demo_grp" {
  name        = "demo_grp"
} 

resource "aci_epg_to_static_path" "foo" {
  application_epg_dn = "uni/tn-abr_tenant/ap-abr_ap/epg-abr_epg"
  tdn = "topology/pod-1/protpaths-101-104/pathep-[${aci_leaf_access_bundle_policy_group.foo.name}]"
  encap = "vlan-1500"
}
```

Please let me know if this fixes your issue and if I misunderstood the issue, please expand the explanation a bit. Also configuration snippets would be appreciated.

Kind regard,

Akini

**Comment by MyUsernameIsTakenAgain** [comment]
Wonderful !
Many thanks, it seems working, at least in Terrafrom code :)) i had mistaken the tDn path as I tried to copy it from the GUI which was wrong, now I see the right path as you stated it, it is located under the object store browser as well.

Regards

**Comment by akinross** [comment]
Good to hear, I have added some additional examples to hopefully clarify it a bit more. If you have any suggestions on the examples added in the attached PR please let me know.
