### ISSUE TITLE
[documentation bug] Document VLAN format for aci_ranges resource

### ISSUE THREAD

**Issue by cpaggen** [CiscoDevNet/terraform-provider-aci#695]
This is a documentation enhancement request, although one could argue it's a documentation bug because it's virtually impossible to use aci_ranges the way it is currently documented at [](https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/ranges)

The documentation really should mention that "to" and "from" parameters expect a VLAN in the following format: "vlan-nnn"; right now the documentation simply mentions from = "example"  and  to = "example" which does not help users.

**Comment by oldguardmd** [comment]
And really, because this is worthless without a VLAN Pool example I would suggest an example like this:

`
resource "aci_vlan_pool" "example_vlan_pool1" {
    name = "exampleVLANPool"
    alloc_mode = "static"
}

resource "aci_ranges" "kcdemo_vlan_range" {
   vlan_pool_dn = aci_vlan_pool.example_vlan_pool1.id
   from = "vlan-501"
   to   = "vlan-501"
   alloc_mode = "static"
   role = "external"
}
`
